remote_theme: SusqCoDAR/susqcodar-theme@main
title: Susquehanna County DAR
description: Susquehanna County chapter of the Daughters of the American Revolution
banner-text: Susquehanna County Chapter, NSDAR, Montrose, PA
webmaster: webmaster@susquehannacountydar.org
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "activities"
      sidebar_suffix: " Activities"
