remote_theme: SusqCoDAR/susqcodar-theme@main
title: Susquehanna County DAR
description: Susquehanna County chapter of the Daughters of the American Revolution
webmaster: webmaster@suscodar.org
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      type: "posts"
    values:
      category: "activities"
