name: 'Update Modification Dates'
run-name: 'Update Modification Dates'

on:
  push

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  update-modified-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update modification dates
        run: ./.github/scripts/update-modified-dates.sh

      - name: 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |+
            Update page modified dates

            NO_UPDATE_MODIFIED_DATE 

